### ISSUE TITLE
Implement remove year as a part of the year dot menu and add year as a floating action button

### ISSUE THREAD

**Issue by assumption** [cpe308-309/Mustang-Manager#107]
Add year will be in the bottom right hand corner of page, with a floating tool-tip describing its functionality. Remove year will be added to the menu containing toggle summer.

**Comment by BaconPartyWOOOO** [comment]
Closed in commits: 0ac55bdd1064be7be7d698148908137852283f4f 55b515dd35b57283f6c5777c94ca324c62c433dc 37c780b18af449cd291d81338605f5af3da119c4 5587fda0970cd64510cd84242eadac197d15b115 d625163b10d1a46dd8a4d39add2ebd081f798820 2e64c089f752be650c1a44dbc523b30e3803fed1
